import "./globals.css";
import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import localFont from 'next/font/local'
 

const quicksans = localFont({ src: './QuicksansAccurateICGFill.ttf', variable:'--font-quicksans' })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${quicksans.variable} font-sans`}>
			<body
				className={` dark:bg-black bg-white scrollbar-thin scrollbar-thumb-[#DCE4FF] scrollbar-thin-rounded-md scrollbar-track-white  `}
			>
				{children}
      <ToastContainer position="bottom-right" />
			</body>
		</html>
	);
}
